### ISSUE TITLE
add another set of chess pieces

### ISSUE THREAD

**Issue by pheyvaer** [pheyvaer/solid-chess#30]

**Comment by akuckartz** [comment]
?!

**Comment by pheyvaer** [comment]
Users will be able to switch between two themes of pieces and board (see [this branch](https://github.com/pheyvaer/solid-chess/tree/release/0.0.5)). This leads to another interaction with the PODs to tackle: saving app-specific data which are unrelated to a specific chess game, e.g., user preferences. See also #31

**Comment by pheyvaer** [comment]
Fixed in [v0.0.5](https://github.com/pheyvaer/solid-chess/releases/tag/v0.0.5)
