### ISSUE TITLE
ontology for join requests

### ISSUE THREAD

**Issue by pheyvaer** [pheyvaer/solid-chess#32]
At the moment we use `http://example.org/game/` as namespace for join requests. Thus, we need a real ontology to model the requests to join the game. We either find an existing one or make one ourselves.

**Comment by akuckartz** [comment]
?

**Comment by pheyvaer** [comment]
@akuckartz Updated the initial description of the issue 😉

**Comment by pheyvaer** [comment]
Schema.org has what we need I think:

- [InviteAction](http://schema.org/InviteAction): used to invite a friend to join the chess game
- [RsvpAction](http://schema.org/RsvpAction): used to reply to an `InviteAction` via [`schema:result`](http://schema.org/).
